spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:100}
      query:
        fail_on_pagination_over_collection_fetch: true
    open-in-view: false
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:jojoldu;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      auto-commit: false
      maximumPoolSize: 10
logging:
  level:
    org:
      springframework:
        batch: DEBUG
